package org.kvkit.model;
// Generated 15 Oct, 2013 10:47:56 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Marks generated by hbm2java
 */
public class Marks  implements java.io.Serializable {


     private Integer marksId;
     private int userId;
     private Date attendedDate;
     private Integer marks;
     private Integer atendedMins;

    public Marks() {
    }

	
    public Marks(int userId) {
        this.userId = userId;
    }
    public Marks(int userId, Date attendedDate, Integer marks, Integer atendedMins) {
       this.userId = userId;
       this.attendedDate = attendedDate;
       this.marks = marks;
       this.atendedMins = atendedMins;
    }
   
    public Integer getMarksId() {
        return this.marksId;
    }
    
    public void setMarksId(Integer marksId) {
        this.marksId = marksId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Date getAttendedDate() {
        return this.attendedDate;
    }
    
    public void setAttendedDate(Date attendedDate) {
        this.attendedDate = attendedDate;
    }
    public Integer getMarks() {
        return this.marks;
    }
    
    public void setMarks(Integer marks) {
        this.marks = marks;
    }
    public Integer getAtendedMins() {
        return this.atendedMins;
    }
    
    public void setAtendedMins(Integer atendedMins) {
        this.atendedMins = atendedMins;
    }




}


