package org.kvkit.model;
// Generated 15 Oct, 2013 10:47:56 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String email;
     private Date joinedDate;

    public Users() {
    }

    public Users(String userName, String email, Date joinedDate) {
       this.userName = userName;
       this.email = email;
       this.joinedDate = joinedDate;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getJoinedDate() {
        return this.joinedDate;
    }
    
    public void setJoinedDate(Date joinedDate) {
        this.joinedDate = joinedDate;
    }




}


